/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayManagement.java
 *
 * Created on 19 oct. 2010, 12:58:09
 */
package simulationopinion;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.WindowConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Teddie
 */
public class DisplayManagement extends javax.swing.JFrame {

    private DefaultPieDataset data;
    private String pathSave;
    private String pathLoad;
    public TreeMap<Integer, Color> listColorToOpinion;
    private ArrayList<JLabel> listLabel;
    private DisplayEnvironment dispEnv;
    private JFrame Display;

    /** Creates new form DisplayManagement */
    public DisplayManagement(ArrayList<Agent> listAgent, Controller controller) {
        initComponents();
        this.setVisible(false);
        this.setTitle("iOpinion");
        this.InitialisationColor();
        this.InitialisationPiePlot();
        jButtonOk.addActionListener(controller);
        jButtonStart.addActionListener(controller);
        jButtonStop.addActionListener(controller);
        jFrameWelcome.setTitle("Bienvenue sur iOpinion");
        jFrameWelcome.setVisible(true);
        dispEnv = new DisplayEnvironment(listAgent, listColorToOpinion);
        dispEnv.setBackground(Color.WHITE);
        dispEnv.setPreferredSize(new Dimension(500, 500));
        Display = new JFrame();
        Display.setResizable(false);
        Display.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        Display.setTitle("Environnement");

        Display.setContentPane(dispEnv);
        listLabel = new ArrayList<JLabel>();
        listLabel.add(jLabelNbOpinion0);
        listLabel.add(jLabelNbOpinion1);
        listLabel.add(jLabelNbOpinion2);
        listLabel.add(jLabelNbOpinion3);
        listLabel.add(jLabelNbOpinion4);
        listLabel.add(jLabelNbOpinion5);
        listLabel.add(jLabelNbOpinion6);
        listLabel.add(jLabelNbOpinion7);
        listLabel.add(jLabelNbOpinion8);
        listLabel.add(jLabelNbOpinion9);
        this.UpdateLabelSlide(jSliderNbAgent, jLabelSlideNbAgent);
        this.UpdateLabelSlide(jSliderDimEnv, jLabelSliderDImEnv);
        this.UpdateLabelSlide(jSliderArea, jLabelSliderArea);
        this.UpdateLabelSlide(jSliderStep, jLabelSliderStep);
        this.UpdateLabelSlide(jSliderWaitTime, jLabelSliderWaitTime);
        this.UpdateLabelSlide(jSliderTrust, jLabelSliderTrust);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /**
     * Initialization Color
     * @ author Alexandre C, Teddie
     */
    private void InitialisationColor() {
        listColorToOpinion = new TreeMap<Integer, Color>();
        listColorToOpinion.put(0, Color.DARK_GRAY);
        listColorToOpinion.put(1, Color.BLUE);
        listColorToOpinion.put(2, Color.YELLOW);
        listColorToOpinion.put(3, Color.RED);
        listColorToOpinion.put(4, Color.PINK);
        listColorToOpinion.put(5, Color.ORANGE);
        listColorToOpinion.put(6, Color.GREEN);
        listColorToOpinion.put(7, Color.MAGENTA);
        listColorToOpinion.put(8, Color.GRAY);
        listColorToOpinion.put(9, Color.CYAN);
    }

    /**
     * Initialization of Pie Plot
     * @ author Alexandre F, Teddie
     */
    private void InitialisationPiePlot() {
        data = new DefaultPieDataset();
        data.setValue("Opinion0", 0);
        data.setValue("Opinion1", 0);
        data.setValue("Opinion2", 0);
        data.setValue("Opinion3", 0);
        data.setValue("Opinion4", 0);
        data.setValue("Opinion5", 0);
        data.setValue("Opinion6", 0);
        data.setValue("Opinion7", 0);
        data.setValue("Opinion8", 0);
        data.setValue("Opinion9", 0);
        JFreeChart g = ChartFactory.createPieChart3D("Représentation graphique du nombre d'agents par opinion", data, true, true, false);
        ChartPanel c = new ChartPanel(g);
        PiePlot3D plot = (PiePlot3D) g.getPlot();
        plot.setForegroundAlpha((float) 0.6);
        for (Map.Entry<Integer, Color> e : listColorToOpinion.entrySet()) {
            plot.setSectionPaint("Opinion " + e.getKey(), e.getValue());
        }
        BoxLayout Box = new BoxLayout(jPanelGraph, BoxLayout.PAGE_AXIS);
        jPanelGraph.setLayout(Box);
        this.jPanelGraph.add(c);
    }

    /**
     * @author Teddie
     * @param listAgentToOpinion
     */
    public void update(TreeMap<Integer, ArrayList<Agent>> listAgentToOpinion) {
        for (Map.Entry<Integer, ArrayList<Agent>> e : listAgentToOpinion.entrySet()) {
            Integer nb = e.getValue().size();
            listLabel.get(e.getKey()).setText(nb.toString());
            data.setValue("Opinion" + e.getKey(), nb);
            dispEnv.repaint();
        }
    }

    /**
     * @author Alexandre C, Teddie
     * @param j
     * @param l
     */
    private void UpdateLabelSlide(JSlider j, JLabel l) {
        Integer tmp = j.getValue();
        l.setText(tmp.toString());
    }
    //--------------------GETTER FOR SIMULATION-----------------//

    public int getNbAgent() {
        return jSliderNbAgent.getValue();
    }

    public int getWaitTime() {
        return jSliderWaitTime.getValue();
    }

    public int getDimEnv() {
        return jSliderDimEnv.getValue();
    }

    public int getArea() {
        return jSliderArea.getValue();
    }

    public int getStep() {
        return jSliderStep.getValue();
    }

    public int getTrust() {
        return jSliderTrust.getValue();
    }

    public String getPath() {
        return this.pathSave;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameWelcome = new javax.swing.JFrame();
        jPanelWelcome = new javax.swing.JPanel();
        jLabelInitnbAgent = new javax.swing.JLabel();
        jLabelWaitTime = new javax.swing.JLabel();
        jLabelEnvDim = new javax.swing.JLabel();
        jLabelInteraction = new javax.swing.JLabel();
        jLabelPas = new javax.swing.JLabel();
        jLabelTrust = new javax.swing.JLabel();
        jSliderNbAgent = new javax.swing.JSlider();
        jSliderWaitTime = new javax.swing.JSlider();
        jSliderDimEnv = new javax.swing.JSlider();
        jSliderArea = new javax.swing.JSlider();
        jSliderStep = new javax.swing.JSlider();
        jSliderTrust = new javax.swing.JSlider();
        jCheckBoxSave = new javax.swing.JCheckBox();
        jButtonOk = new javax.swing.JButton();
        jButtonLoad1 = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jLabelSliderTrust = new javax.swing.JLabel();
        jLabelSliderWaitTime = new javax.swing.JLabel();
        jLabelSliderArea = new javax.swing.JLabel();
        jLabelSliderStep = new javax.swing.JLabel();
        jLabelSliderDImEnv = new javax.swing.JLabel();
        jLabelSlideNbAgent = new javax.swing.JLabel();
        jFileChooserSave = new javax.swing.JFileChooser();
        jFileChooserOpen = new javax.swing.JFileChooser();
        jPanelGraph = new javax.swing.JPanel();
        jPanelStat = new javax.swing.JPanel();
        jLabelOpinion0 = new javax.swing.JLabel();
        jLabelOpinion1 = new javax.swing.JLabel();
        jLabelOpinion2 = new javax.swing.JLabel();
        jLabelOpinion3 = new javax.swing.JLabel();
        jLabelOpinion5 = new javax.swing.JLabel();
        jLabelOpinion4 = new javax.swing.JLabel();
        jLabelOpinion6 = new javax.swing.JLabel();
        jLabelOpinion7 = new javax.swing.JLabel();
        jLabelOpinion8 = new javax.swing.JLabel();
        jLabelOpinion9 = new javax.swing.JLabel();
        jLabelNbOpinion1 = new javax.swing.JLabel();
        jLabelNbOpinion4 = new javax.swing.JLabel();
        jLabelNbOpinion7 = new javax.swing.JLabel();
        jLabelNbOpinion8 = new javax.swing.JLabel();
        jLabelNbOpinion5 = new javax.swing.JLabel();
        jLabelNbOpinion2 = new javax.swing.JLabel();
        jLabelNbOpinion6 = new javax.swing.JLabel();
        jLabelNbOpinion9 = new javax.swing.JLabel();
        jLabelNbOpinion3 = new javax.swing.JLabel();
        jLabelNbOpinion0 = new javax.swing.JLabel();
        jPanelAction = new javax.swing.JPanel();
        jLabelAgent = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jLabelActionNbAgent = new javax.swing.JLabel();
        jLabelInitWait = new javax.swing.JLabel();
        jLabelInitDimEnv = new javax.swing.JLabel();
        jLabelIniArea = new javax.swing.JLabel();
        jLabellnitStep = new javax.swing.JLabel();
        jLabelInitTrust = new javax.swing.JLabel();
        jLabelInitNbAgent = new javax.swing.JLabel();
        jLabelInitNbWait = new javax.swing.JLabel();
        jLabelInitNbDimEnv = new javax.swing.JLabel();
        jLabelInitNbArea = new javax.swing.JLabel();
        jLabelInitNbStep = new javax.swing.JLabel();
        jLabelInitNbTrust = new javax.swing.JLabel();
        jCheckBoxDisplay = new javax.swing.JCheckBox();

        jFrameWelcome.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrameWelcome.setTitle("Bienvenue");
        jFrameWelcome.setMinimumSize(new java.awt.Dimension(598, 455));
        jFrameWelcome.setName("Welcome"); // NOI18N

        jPanelWelcome.setPreferredSize(new java.awt.Dimension(514, 250));

        jLabelInitnbAgent.setText("Nombre d'agents :");

        jLabelWaitTime.setText("Temps d'attente :");

        jLabelEnvDim.setText("Dimension de l'environnement :");

        jLabelInteraction.setText("Zone d'interaction :");

        jLabelPas.setText("Pas de déplacement :");

        jLabelTrust.setText("Indice de confiance :");

        jSliderNbAgent.setMaximum(500);
        jSliderNbAgent.setMinimum(2);
        jSliderNbAgent.setValue(250);
        jSliderNbAgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderNbAgentMouseClicked(evt);
            }
        });
        jSliderNbAgent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderNbAgentMouseDragged(evt);
            }
        });
        jSliderNbAgent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderNbAgentKeyPressed(evt);
            }
        });

        jSliderWaitTime.setMaximum(30);
        jSliderWaitTime.setMinimum(1);
        jSliderWaitTime.setValue(5);
        jSliderWaitTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderWaitTimeMouseClicked(evt);
            }
        });
        jSliderWaitTime.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderWaitTimeMouseDragged(evt);
            }
        });
        jSliderWaitTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderWaitTimeKeyPressed(evt);
            }
        });

        jSliderDimEnv.setMaximum(500);
        jSliderDimEnv.setMinimum(50);
        jSliderDimEnv.setValue(250);
        jSliderDimEnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderDimEnvMouseClicked(evt);
            }
        });
        jSliderDimEnv.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderDimEnvMouseDragged(evt);
            }
        });
        jSliderDimEnv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderDimEnvKeyPressed(evt);
            }
        });

        jSliderArea.setMaximum(50);
        jSliderArea.setMinimum(1);
        jSliderArea.setValue(25);
        jSliderArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderAreaMouseClicked(evt);
            }
        });
        jSliderArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderAreaMouseDragged(evt);
            }
        });
        jSliderArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderAreaKeyPressed(evt);
            }
        });

        jSliderStep.setMaximum(2);
        jSliderStep.setMinimum(1);
        jSliderStep.setValue(1);
        jSliderStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderStepMouseClicked(evt);
            }
        });
        jSliderStep.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderStepMouseDragged(evt);
            }
        });
        jSliderStep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderStepKeyPressed(evt);
            }
        });

        jSliderTrust.setMaximum(5);
        jSliderTrust.setMinimum(1);
        jSliderTrust.setValue(3);
        jSliderTrust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderTrustMouseClicked(evt);
            }
        });
        jSliderTrust.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTrustMouseDragged(evt);
            }
        });
        jSliderTrust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderTrustKeyPressed(evt);
            }
        });

        jCheckBoxSave.setText("Sauvegarder la simulation ");
        jCheckBoxSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaveActionPerformed(evt);
            }
        });

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonLoad1.setText("Charger");
        jButtonLoad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoad1ActionPerformed(evt);
            }
        });

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabelInfo.setText("Choix des paramètres de la simulation");

        jLabelSliderTrust.setText("0");

        jLabelSliderWaitTime.setText("0");

        jLabelSliderArea.setText("0");

        jLabelSliderStep.setText("0");

        jLabelSliderDImEnv.setText("0");

        jLabelSlideNbAgent.setText("0");

        javax.swing.GroupLayout jPanelWelcomeLayout = new javax.swing.GroupLayout(jPanelWelcome);
        jPanelWelcome.setLayout(jPanelWelcomeLayout);
        jPanelWelcomeLayout.setHorizontalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWelcomeLayout.createSequentialGroup()
                        .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWaitTime)
                            .addComponent(jLabelInitnbAgent))
                        .addGap(109, 109, 109)
                        .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSliderNbAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jSliderWaitTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jSliderDimEnv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jSliderArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jSliderStep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jSliderTrust, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                    .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                        .addComponent(jLabelEnvDim)
                        .addGap(287, 287, 287))
                    .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                        .addComponent(jLabelInteraction)
                        .addGap(375, 375, 375))
                    .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                        .addComponent(jLabelPas)
                        .addGap(362, 362, 362))
                    .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                        .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTrust)
                            .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                                .addComponent(jCheckBoxSave)
                                .addGap(112, 112, 112)
                                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLoad1)))
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSliderDImEnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSliderTrust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSliderStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSliderArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSliderWaitTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSlideNbAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabelInfo)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanelWelcomeLayout.setVerticalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWelcomeLayout.createSequentialGroup()
                .addComponent(jLabelInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderNbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInitnbAgent)
                    .addComponent(jLabelSlideNbAgent))
                .addGap(21, 21, 21)
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderWaitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWaitTime)
                    .addComponent(jLabelSliderWaitTime))
                .addGap(18, 18, 18)
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEnvDim)
                    .addComponent(jSliderDimEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSliderDImEnv))
                .addGap(18, 18, 18)
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInteraction)
                    .addComponent(jSliderArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSliderArea))
                .addGap(18, 18, 18)
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPas)
                    .addComponent(jSliderStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSliderStep))
                .addGap(18, 18, 18)
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                        .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTrust)
                            .addComponent(jSliderTrust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxSave)
                            .addComponent(jButtonOk)
                            .addComponent(jButtonLoad1)))
                    .addComponent(jLabelSliderTrust))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jFrameWelcomeLayout = new javax.swing.GroupLayout(jFrameWelcome.getContentPane());
        jFrameWelcome.getContentPane().setLayout(jFrameWelcomeLayout);
        jFrameWelcomeLayout.setHorizontalGroup(
            jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrameWelcomeLayout.setVerticalGroup(
            jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFileChooserSave.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Silmulateur d'opinion");
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanelGraph.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelGraph.setPreferredSize(new java.awt.Dimension(690, 430));

        javax.swing.GroupLayout jPanelGraphLayout = new javax.swing.GroupLayout(jPanelGraph);
        jPanelGraph.setLayout(jPanelGraphLayout);
        jPanelGraphLayout.setHorizontalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jPanelGraphLayout.setVerticalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jPanelStat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelOpinion0.setText("Opinion 0 :");

        jLabelOpinion1.setText("Opinion 1 :");

        jLabelOpinion2.setText("Opinion 2 :");

        jLabelOpinion3.setText("Opinion 3 :");

        jLabelOpinion5.setText("Opinion 5 :");

        jLabelOpinion4.setText("Opinion 4 :");

        jLabelOpinion6.setText("Opinion 6 :");

        jLabelOpinion7.setText("Opinion 7 :");

        jLabelOpinion8.setText("Opinion 8 :");

        jLabelOpinion9.setText("Opinion 9 :");

        jLabelNbOpinion1.setText("0");

        jLabelNbOpinion4.setText("0");

        jLabelNbOpinion7.setText("0");

        jLabelNbOpinion8.setText("0");

        jLabelNbOpinion5.setText("0");

        jLabelNbOpinion2.setText("0");

        jLabelNbOpinion6.setText("0");

        jLabelNbOpinion9.setText("0");

        jLabelNbOpinion3.setText("0");

        jLabelNbOpinion0.setText("0");

        javax.swing.GroupLayout jPanelStatLayout = new javax.swing.GroupLayout(jPanelStat);
        jPanelStat.setLayout(jPanelStatLayout);
        jPanelStatLayout.setHorizontalGroup(
            jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpinion4)
                    .addComponent(jLabelOpinion0)
                    .addComponent(jLabelOpinion8))
                .addGap(18, 18, 18)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNbOpinion8)
                    .addComponent(jLabelNbOpinion0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNbOpinion4))
                .addGap(149, 149, 149)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion5)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion1)
                        .addGap(23, 23, 23))
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNbOpinion1)
                    .addComponent(jLabelNbOpinion5)
                    .addComponent(jLabelNbOpinion9))
                .addGap(154, 154, 154)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpinion6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOpinion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNbOpinion2)
                    .addComponent(jLabelNbOpinion6))
                .addGap(152, 152, 152)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpinion3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOpinion7))
                .addGap(18, 18, 18)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNbOpinion7)
                    .addComponent(jLabelNbOpinion3))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanelStatLayout.setVerticalGroup(
            jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNbOpinion2)
                            .addComponent(jLabelOpinion2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOpinion6)
                            .addComponent(jLabelNbOpinion6)))
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOpinion3)
                            .addComponent(jLabelNbOpinion3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOpinion7)
                            .addComponent(jLabelNbOpinion7))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpinion0)
                    .addComponent(jLabelNbOpinion0, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpinion4)
                    .addComponent(jLabelNbOpinion4))
                .addGap(18, 18, 18)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpinion8)
                    .addComponent(jLabelNbOpinion8))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpinion1)
                    .addComponent(jLabelNbOpinion1))
                .addGap(18, 18, 18)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpinion5)
                    .addComponent(jLabelNbOpinion5))
                .addGap(18, 18, 18)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpinion9)
                    .addComponent(jLabelNbOpinion9))
                .addContainerGap())
        );

        jPanelAction.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelAgent.setText("Nombre d'agents:");

        jButtonStart.setText("Start");
        jButtonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonStartMouseClicked(evt);
            }
        });

        jButtonStop.setText("Stop");

        jLabelInitWait.setText("Temps d'attente");

        jLabelInitDimEnv.setText("Dimension d'environnement:");

        jLabelIniArea.setText("Zone d'interaction:");

        jLabellnitStep.setText("Pas de déplacement:");

        jLabelInitTrust.setText("Indice de confiance:");

        jLabelInitNbAgent.setText("jLabel1");

        jLabelInitNbWait.setText("jLabel2");

        jLabelInitNbDimEnv.setText("jLabel3");

        jLabelInitNbArea.setText("jLabel4");

        jLabelInitNbStep.setText("jLabel5");

        jLabelInitNbTrust.setText("jLabel6");

        jCheckBoxDisplay.setText("Afficher l'environnement");
        jCheckBoxDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxDisplayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelActionLayout = new javax.swing.GroupLayout(jPanelAction);
        jPanelAction.setLayout(jPanelActionLayout);
        jPanelActionLayout.setHorizontalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionLayout.createSequentialGroup()
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActionLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonStart)
                        .addGap(54, 54, 54)
                        .addComponent(jButtonStop))
                    .addGroup(jPanelActionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelActionLayout.createSequentialGroup()
                                .addComponent(jLabelAgent)
                                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelActionLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabelActionNbAgent))
                                    .addGroup(jPanelActionLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelInitNbWait)
                                            .addComponent(jLabelInitNbAgent)
                                            .addComponent(jLabelInitNbDimEnv)
                                            .addComponent(jLabelInitNbArea)
                                            .addComponent(jLabelInitNbStep)
                                            .addComponent(jLabelInitNbTrust)))))
                            .addComponent(jLabelInitWait)
                            .addComponent(jLabelInitDimEnv)
                            .addComponent(jLabellnitStep)
                            .addComponent(jLabelIniArea)
                            .addComponent(jLabelInitTrust)
                            .addComponent(jCheckBoxDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelActionLayout.setVerticalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAgent)
                    .addComponent(jLabelActionNbAgent)
                    .addComponent(jLabelInitNbAgent))
                .addGap(18, 18, 18)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInitWait)
                    .addComponent(jLabelInitNbWait))
                .addGap(18, 18, 18)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInitDimEnv)
                    .addComponent(jLabelInitNbDimEnv))
                .addGap(18, 18, 18)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIniArea)
                    .addComponent(jLabelInitNbArea))
                .addGap(18, 18, 18)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabellnitStep)
                    .addComponent(jLabelInitNbStep))
                .addGap(18, 18, 18)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInitTrust)
                    .addComponent(jLabelInitNbTrust))
                .addGap(17, 17, 17)
                .addComponent(jCheckBoxDisplay)
                .addGap(18, 18, 18)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStart)
                    .addComponent(jButtonStop))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanelGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //------------------EVENT------------------//
    private void jCheckBoxSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaveActionPerformed
        if (jCheckBoxSave.isSelected()) {
            jFileChooserSave.showSaveDialog(jFrameWelcome);
            this.pathSave = jFileChooserSave.getSelectedFile().getAbsolutePath();
        } else {
            this.pathSave = null;
        }
    }//GEN-LAST:event_jCheckBoxSaveActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        Display.setSize(this.getDimEnv() + 20, this.getDimEnv() + 50);
        this.setVisible(true);

        jFrameWelcome.setVisible(false);
        jLabelInitNbAgent.setText(((Integer) jSliderNbAgent.getValue()).toString());
        jLabelInitNbDimEnv.setText(((Integer) jSliderDimEnv.getValue()).toString());
        jLabelInitNbArea.setText(((Integer) jSliderArea.getValue()).toString());
        jLabelInitNbStep.setText(((Integer) jSliderStep.getValue()).toString());
        jLabelInitNbWait.setText(((Integer) jSliderWaitTime.getValue()).toString());
        jLabelInitNbTrust.setText(((Integer) jSliderTrust.getValue()).toString());
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonLoad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoad1ActionPerformed
        jFileChooserOpen.showOpenDialog(jFrameWelcome);
        if (null != jFileChooserOpen.getSelectedFile().getAbsolutePath()) {
            this.pathLoad = jFileChooserOpen.getSelectedFile().getAbsolutePath();
        }
    }//GEN-LAST:event_jButtonLoad1ActionPerformed

    private void jSliderNbAgentMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderNbAgentMouseDragged
        this.UpdateLabelSlide(jSliderNbAgent, jLabelSlideNbAgent);

    }//GEN-LAST:event_jSliderNbAgentMouseDragged

    private void jSliderNbAgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderNbAgentMouseClicked
        this.UpdateLabelSlide(jSliderNbAgent, jLabelSlideNbAgent);
    }//GEN-LAST:event_jSliderNbAgentMouseClicked

    private void jSliderNbAgentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderNbAgentKeyPressed
        this.UpdateLabelSlide(jSliderNbAgent, jLabelSlideNbAgent);
    }//GEN-LAST:event_jSliderNbAgentKeyPressed

    private void jSliderDimEnvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderDimEnvKeyPressed
        this.UpdateLabelSlide(jSliderDimEnv, jLabelSliderDImEnv);
    }//GEN-LAST:event_jSliderDimEnvKeyPressed

    private void jSliderDimEnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDimEnvMouseClicked
        this.UpdateLabelSlide(jSliderDimEnv, jLabelSliderDImEnv);
    }//GEN-LAST:event_jSliderDimEnvMouseClicked

    private void jSliderDimEnvMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDimEnvMouseDragged
        this.UpdateLabelSlide(jSliderDimEnv, jLabelSliderDImEnv);
    }//GEN-LAST:event_jSliderDimEnvMouseDragged

    private void jSliderAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderAreaKeyPressed
        this.UpdateLabelSlide(jSliderArea, jLabelSliderArea);
    }//GEN-LAST:event_jSliderAreaKeyPressed

    private void jSliderAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderAreaMouseClicked
        this.UpdateLabelSlide(jSliderArea, jLabelSliderArea);
    }//GEN-LAST:event_jSliderAreaMouseClicked

    private void jSliderAreaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderAreaMouseDragged
        this.UpdateLabelSlide(jSliderArea, jLabelSliderArea);
    }//GEN-LAST:event_jSliderAreaMouseDragged

    private void jSliderStepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderStepKeyPressed
        this.UpdateLabelSlide(jSliderStep, jLabelSliderStep);
    }//GEN-LAST:event_jSliderStepKeyPressed

    private void jSliderStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderStepMouseClicked
        this.UpdateLabelSlide(jSliderStep, jLabelSliderStep);
    }//GEN-LAST:event_jSliderStepMouseClicked

    private void jSliderStepMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderStepMouseDragged
        this.UpdateLabelSlide(jSliderStep, jLabelSliderStep);
    }//GEN-LAST:event_jSliderStepMouseDragged

    private void jSliderWaitTimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderWaitTimeKeyPressed
        this.UpdateLabelSlide(jSliderWaitTime, jLabelSliderWaitTime);
    }//GEN-LAST:event_jSliderWaitTimeKeyPressed

    private void jSliderWaitTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderWaitTimeMouseClicked
        this.UpdateLabelSlide(jSliderWaitTime, jLabelSliderWaitTime);
    }//GEN-LAST:event_jSliderWaitTimeMouseClicked

    private void jSliderWaitTimeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderWaitTimeMouseDragged
        this.UpdateLabelSlide(jSliderWaitTime, jLabelSliderWaitTime);
    }//GEN-LAST:event_jSliderWaitTimeMouseDragged

    private void jSliderTrustKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderTrustKeyPressed
        this.UpdateLabelSlide(jSliderTrust, jLabelSliderTrust);
    }//GEN-LAST:event_jSliderTrustKeyPressed

    private void jSliderTrustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTrustMouseClicked
        this.UpdateLabelSlide(jSliderTrust, jLabelSliderTrust);
    }//GEN-LAST:event_jSliderTrustMouseClicked

    private void jSliderTrustMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTrustMouseDragged
        this.UpdateLabelSlide(jSliderTrust, jLabelSliderTrust);
    }//GEN-LAST:event_jSliderTrustMouseDragged

    private void jCheckBoxDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxDisplayMouseClicked
        if (jCheckBoxDisplay.isSelected()) {
            Display.setVisible(true);
        } else {
            Display.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxDisplayMouseClicked

    private void jButtonStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStartMouseClicked
        jButtonStart.setEnabled(false);
    }//GEN-LAST:event_jButtonStartMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoad1;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JCheckBox jCheckBoxDisplay;
    private javax.swing.JCheckBox jCheckBoxSave;
    private javax.swing.JFileChooser jFileChooserOpen;
    private javax.swing.JFileChooser jFileChooserSave;
    private javax.swing.JFrame jFrameWelcome;
    private javax.swing.JLabel jLabelActionNbAgent;
    private javax.swing.JLabel jLabelAgent;
    private javax.swing.JLabel jLabelEnvDim;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelIniArea;
    private javax.swing.JLabel jLabelInitDimEnv;
    private javax.swing.JLabel jLabelInitNbAgent;
    private javax.swing.JLabel jLabelInitNbArea;
    private javax.swing.JLabel jLabelInitNbDimEnv;
    private javax.swing.JLabel jLabelInitNbStep;
    private javax.swing.JLabel jLabelInitNbTrust;
    private javax.swing.JLabel jLabelInitNbWait;
    private javax.swing.JLabel jLabelInitTrust;
    private javax.swing.JLabel jLabelInitWait;
    private javax.swing.JLabel jLabelInitnbAgent;
    private javax.swing.JLabel jLabelInteraction;
    private javax.swing.JLabel jLabelNbOpinion0;
    private javax.swing.JLabel jLabelNbOpinion1;
    private javax.swing.JLabel jLabelNbOpinion2;
    private javax.swing.JLabel jLabelNbOpinion3;
    private javax.swing.JLabel jLabelNbOpinion4;
    private javax.swing.JLabel jLabelNbOpinion5;
    private javax.swing.JLabel jLabelNbOpinion6;
    private javax.swing.JLabel jLabelNbOpinion7;
    private javax.swing.JLabel jLabelNbOpinion8;
    private javax.swing.JLabel jLabelNbOpinion9;
    private javax.swing.JLabel jLabelOpinion0;
    private javax.swing.JLabel jLabelOpinion1;
    private javax.swing.JLabel jLabelOpinion2;
    private javax.swing.JLabel jLabelOpinion3;
    private javax.swing.JLabel jLabelOpinion4;
    private javax.swing.JLabel jLabelOpinion5;
    private javax.swing.JLabel jLabelOpinion6;
    private javax.swing.JLabel jLabelOpinion7;
    private javax.swing.JLabel jLabelOpinion8;
    private javax.swing.JLabel jLabelOpinion9;
    private javax.swing.JLabel jLabelPas;
    private javax.swing.JLabel jLabelSlideNbAgent;
    private javax.swing.JLabel jLabelSliderArea;
    private javax.swing.JLabel jLabelSliderDImEnv;
    private javax.swing.JLabel jLabelSliderStep;
    private javax.swing.JLabel jLabelSliderTrust;
    private javax.swing.JLabel jLabelSliderWaitTime;
    private javax.swing.JLabel jLabelTrust;
    private javax.swing.JLabel jLabelWaitTime;
    private javax.swing.JLabel jLabellnitStep;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelGraph;
    private javax.swing.JPanel jPanelStat;
    private javax.swing.JPanel jPanelWelcome;
    private javax.swing.JSlider jSliderArea;
    private javax.swing.JSlider jSliderDimEnv;
    private javax.swing.JSlider jSliderNbAgent;
    private javax.swing.JSlider jSliderStep;
    private javax.swing.JSlider jSliderTrust;
    private javax.swing.JSlider jSliderWaitTime;
    // End of variables declaration//GEN-END:variables
}
