/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayManagement.java
 *
 * Created on 19 oct. 2010, 12:58:09
 */
package simulationopinion;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Teddie
 */
public class DisplayManagement extends javax.swing.JFrame {

    private DefaultPieDataset data;
    private String pathSave;
    private TreeMap <Integer,Color> listColorToOpinion;
    private ArrayList<JLabel> listLabel;

    /** Creates new form DisplayManagement */
    public DisplayManagement(ArrayList<Agent> listAgent) {
        initComponents();
        this.setVisible(false);
        this.InitialisationColor();
        this.InitialisationPiePlot();
        jFrameWelcome.setVisible(true);
        DisplayEnvironment e= new DisplayEnvironment(listAgent, listColorToOpinion);
        e.paint(null);// A REVOIR
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void InitialisationColor(){
        listColorToOpinion = new TreeMap <Integer,Color>();
        listColorToOpinion.put(1,Color.BLUE);
        listColorToOpinion.put(2,Color.YELLOW);
        listColorToOpinion.put(3,Color.RED);
        listColorToOpinion.put(4,Color.PINK);
        listColorToOpinion.put(5,Color.ORANGE);
        listColorToOpinion.put(6,Color.GREEN);
        listColorToOpinion.put(7,Color.MAGENTA);
        listColorToOpinion.put(8,Color.GRAY);
        listColorToOpinion.put(9,Color.CYAN);
    }

    private void InitialisationPiePlot(){
        data = new DefaultPieDataset();
        data.setValue("Opinion 1", 11.1);
        data.setValue("Opinion 2", 11.1);
        data.setValue("Opinion 3", 11.1);
        data.setValue("Opinion 4", 11.1);
        data.setValue("Opinion 5", 11.1);
        data.setValue("Opinion 6", 11.1);
        data.setValue("Opinion 7", 11.1);
        data.setValue("Opinion 8", 11.1);
        data.setValue("Opinion 9", 11.1);
        JFreeChart g = ChartFactory.createPieChart3D("Représentation graphique du nombre de personnes par opinions", data, true, true, false);
        ChartPanel c = new ChartPanel(g);
        PiePlot3D plot = (PiePlot3D) g.getPlot();
        plot.setForegroundAlpha((float) 0.6);
        for(Map.Entry<Integer,Color> e:listColorToOpinion.entrySet()){
            plot.setSectionPaint("Opinion "+e.getKey(), e.getValue());}
        BoxLayout Box = new BoxLayout(jPanelGraph, BoxLayout.PAGE_AXIS);
        jPanelGraph.setLayout(Box);
        this.jPanelGraph.add(c);
    }

    private void modificationPiePlot(float o1,float o2,float o3,float o4,float o5,float o6,float o7,float o8,float o9){
        data.setValue("Opinion 1", o1);
        data.setValue("Opinion 2", o2);
        data.setValue("Opinion 3", o3);
        data.setValue("Opinion 4", o4);
        data.setValue("Opinion 5", o5);
        data.setValue("Opinion 6", o6);
        data.setValue("Opinion 7", o7);
        data.setValue("Opinion 8", o8);
        data.setValue("Opinion 9", o9);
    }



    private void update(TreeMap<Integer,ArrayList<Agent>> listAgentToOpinion){
        int nb;
        for(Map.Entry<Integer,ArrayList<Agent>> e :listAgentToOpinion.entrySet() ){
            nb=e.getValue().size();

        }
    }

    private double percent(float nb, float total){
        return nb*100/total;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameWelcome = new javax.swing.JFrame();
        jLabelInfo = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jLabelInitnbAgent = new javax.swing.JLabel();
        jLabelTrust = new javax.swing.JLabel();
        jLabelEnvDim = new javax.swing.JLabel();
        jLabelInteraction = new javax.swing.JLabel();
        jLabelPas = new javax.swing.JLabel();
        jTextFieldInitNbAgent = new javax.swing.JTextField();
        jTextFieldTrust = new javax.swing.JTextField();
        jTextFieldEnvSize = new javax.swing.JTextField();
        jTextFieldInteraction = new javax.swing.JTextField();
        jTextFieldPas = new javax.swing.JTextField();
        jButtonLoad1 = new javax.swing.JButton();
        jCheckBoxSave = new javax.swing.JCheckBox();
        jFileChooserSave = new javax.swing.JFileChooser();
        jFileChooserOpen = new javax.swing.JFileChooser();
        jPanelGraph = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelOpinion1 = new javax.swing.JLabel();
        jLabelOpinion2 = new javax.swing.JLabel();
        jLabelOpinion3 = new javax.swing.JLabel();
        jLabelOpinion5 = new javax.swing.JLabel();
        jLabelOpinion4 = new javax.swing.JLabel();
        jLabelOpinion6 = new javax.swing.JLabel();
        jLabelOpinion7 = new javax.swing.JLabel();
        jLabelOpinion8 = new javax.swing.JLabel();
        jLabelOpinion9 = new javax.swing.JLabel();
        jLabelNbOpinion1 = new javax.swing.JLabel();
        jLabelNbOpinion4 = new javax.swing.JLabel();
        jLabelNbOpinion7 = new javax.swing.JLabel();
        jLabelNbOpinion8 = new javax.swing.JLabel();
        jLabelNbOpinion5 = new javax.swing.JLabel();
        jLabelNbOpinion2 = new javax.swing.JLabel();
        jLabelNbOpinion6 = new javax.swing.JLabel();
        jLabelNbOpinion9 = new javax.swing.JLabel();
        jLabelNbOpinion3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelnbAgent = new javax.swing.JLabel();
        jLabelAgent = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();

        jFrameWelcome.setTitle("Bienvenue");
        jFrameWelcome.setMinimumSize(new java.awt.Dimension(515, 375));
        jFrameWelcome.setName("Welcome"); // NOI18N

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelInfo.setText("Choix des paramètres de la simulation");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelInitnbAgent.setText("Nombre d'agents:");

        jLabelTrust.setText("Indice de confiance:");

        jLabelEnvDim.setText("Dimension de l'environnement:");

        jLabelInteraction.setText("Zone d'interaction:");

        jLabelPas.setText("Pas de déplacement:");

        jTextFieldInitNbAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInitNbAgentActionPerformed(evt);
            }
        });

        jButtonLoad1.setText("Load");
        jButtonLoad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoad1ActionPerformed(evt);
            }
        });

        jCheckBoxSave.setText("Sauvegarder la simulation ");
        jCheckBoxSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameWelcomeLayout = new javax.swing.GroupLayout(jFrameWelcome.getContentPane());
        jFrameWelcome.getContentPane().setLayout(jFrameWelcomeLayout);
        jFrameWelcomeLayout.setHorizontalGroup(
            jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabelInfo)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameWelcomeLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameWelcomeLayout.createSequentialGroup()
                        .addComponent(jCheckBoxSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOk)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonLoad1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameWelcomeLayout.createSequentialGroup()
                        .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTrust)
                            .addComponent(jLabelEnvDim)
                            .addComponent(jLabelInteraction)
                            .addComponent(jLabelPas)
                            .addComponent(jLabelInitnbAgent))
                        .addGap(135, 135, 135)
                        .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldInitNbAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jTextFieldTrust)
                            .addComponent(jTextFieldEnvSize)
                            .addComponent(jTextFieldInteraction)
                            .addComponent(jTextFieldPas))
                        .addGap(48, 48, 48))))
        );
        jFrameWelcomeLayout.setVerticalGroup(
            jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfo)
                .addGap(55, 55, 55)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInitNbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInitnbAgent))
                .addGap(18, 18, 18)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrust)
                    .addComponent(jTextFieldTrust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnvDim)
                    .addComponent(jTextFieldEnvSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInteraction)
                    .addComponent(jTextFieldInteraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPas)
                    .addComponent(jTextFieldPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonLoad1)
                    .addComponent(jCheckBoxSave))
                .addContainerGap())
        );

        jFileChooserSave.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Silmulateur d'opinion");
        setMinimumSize(new java.awt.Dimension(1280, 768));

        javax.swing.GroupLayout jPanelGraphLayout = new javax.swing.GroupLayout(jPanelGraph);
        jPanelGraph.setLayout(jPanelGraphLayout);
        jPanelGraphLayout.setHorizontalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        jPanelGraphLayout.setVerticalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        jLabelOpinion1.setText("Opinion 1");

        jLabelOpinion2.setText("Opinion 2");

        jLabelOpinion3.setText("Opinion 3");

        jLabelOpinion5.setText("Opinion 5");

        jLabelOpinion4.setText("Opinion 4");

        jLabelOpinion6.setText("Opinion 6");

        jLabelOpinion7.setText("Opinion 7");

        jLabelOpinion8.setText("Opinion 8");

        jLabelOpinion9.setText("opinion 9");

        jLabelNbOpinion1.setText("1");

        jLabelNbOpinion4.setText(" 4");

        jLabelNbOpinion7.setText(" 7");

        jLabelNbOpinion8.setText("8");

        jLabelNbOpinion5.setText("5");

        jLabelNbOpinion2.setText("2");

        jLabelNbOpinion6.setText("6");

        jLabelNbOpinion9.setText("9");

        jLabelNbOpinion3.setText("3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpinion1)
                    .addComponent(jLabelNbOpinion7)
                    .addComponent(jLabelOpinion7)
                    .addComponent(jLabelNbOpinion4)
                    .addComponent(jLabelOpinion4)
                    .addComponent(jLabelNbOpinion1))
                .addGap(197, 197, 197)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpinion2)
                    .addComponent(jLabelNbOpinion2)
                    .addComponent(jLabelOpinion5)
                    .addComponent(jLabelNbOpinion5)
                    .addComponent(jLabelOpinion8)
                    .addComponent(jLabelNbOpinion8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpinion3)
                    .addComponent(jLabelNbOpinion3)
                    .addComponent(jLabelOpinion6)
                    .addComponent(jLabelNbOpinion6)
                    .addComponent(jLabelOpinion9)
                    .addComponent(jLabelNbOpinion9))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpinion1)
                    .addComponent(jLabelOpinion3)
                    .addComponent(jLabelOpinion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbOpinion1)
                    .addComponent(jLabelNbOpinion2)
                    .addComponent(jLabelNbOpinion3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpinion4)
                    .addComponent(jLabelOpinion6)
                    .addComponent(jLabelOpinion5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbOpinion4)
                    .addComponent(jLabelNbOpinion6)
                    .addComponent(jLabelNbOpinion5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpinion7)
                    .addComponent(jLabelOpinion9)
                    .addComponent(jLabelOpinion8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbOpinion7)
                    .addComponent(jLabelNbOpinion9)
                    .addComponent(jLabelNbOpinion8))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabelnbAgent.setText("10000000");

        jLabelAgent.setText("Nombre d'agents");

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonStop.setText("Load");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAgent)
                    .addComponent(jButtonStart))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonStop))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabelnbAgent)))
                .addGap(336, 336, 336))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAgent)
                    .addComponent(jLabelnbAgent))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStart)
                    .addComponent(jButtonStop))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGraph, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed

}//GEN-LAST:event_jButtonStartActionPerformed

    private void jTextFieldInitNbAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInitNbAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInitNbAgentActionPerformed

    private void jCheckBoxSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSaveActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
    // TODO add your handling code here:
        if(jCheckBoxSave.isSelected())
            jFileChooserSave.showSaveDialog(jFrameWelcome);
            pathSave=jFileChooserSave.getSelectedFile().getAbsolutePath();
        
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonLoad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoad1ActionPerformed
        // TODO add your handling code here:
        jFileChooserOpen.showOpenDialog(jFrameWelcome);
    }//GEN-LAST:event_jButtonLoad1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoad1;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JCheckBox jCheckBoxSave;
    private javax.swing.JFileChooser jFileChooserOpen;
    private javax.swing.JFileChooser jFileChooserSave;
    private javax.swing.JFrame jFrameWelcome;
    private javax.swing.JLabel jLabelAgent;
    private javax.swing.JLabel jLabelEnvDim;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInitnbAgent;
    private javax.swing.JLabel jLabelInteraction;
    private javax.swing.JLabel jLabelNbOpinion1;
    private javax.swing.JLabel jLabelNbOpinion2;
    private javax.swing.JLabel jLabelNbOpinion3;
    private javax.swing.JLabel jLabelNbOpinion4;
    private javax.swing.JLabel jLabelNbOpinion5;
    private javax.swing.JLabel jLabelNbOpinion6;
    private javax.swing.JLabel jLabelNbOpinion7;
    private javax.swing.JLabel jLabelNbOpinion8;
    private javax.swing.JLabel jLabelNbOpinion9;
    private javax.swing.JLabel jLabelOpinion1;
    private javax.swing.JLabel jLabelOpinion2;
    private javax.swing.JLabel jLabelOpinion3;
    private javax.swing.JLabel jLabelOpinion4;
    private javax.swing.JLabel jLabelOpinion5;
    private javax.swing.JLabel jLabelOpinion6;
    private javax.swing.JLabel jLabelOpinion7;
    private javax.swing.JLabel jLabelOpinion8;
    private javax.swing.JLabel jLabelOpinion9;
    private javax.swing.JLabel jLabelPas;
    private javax.swing.JLabel jLabelTrust;
    private javax.swing.JLabel jLabelnbAgent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelGraph;
    private javax.swing.JTextField jTextFieldEnvSize;
    private javax.swing.JTextField jTextFieldInitNbAgent;
    private javax.swing.JTextField jTextFieldInteraction;
    private javax.swing.JTextField jTextFieldPas;
    private javax.swing.JTextField jTextFieldTrust;
    // End of variables declaration//GEN-END:variables
}
