/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayManagement.java
 *
 * Created on 19 oct. 2010, 12:58:09
 */
package simulationopinion;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JSlider;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Teddie
 */
public class DisplayManagement extends javax.swing.JFrame {

    private DefaultPieDataset data;
    private String pathSave;
    public TreeMap<Integer, Color> listColorToOpinion;
    private ArrayList<JLabel> listLabel;
    private DisplayEnvironment dispEnv;

    /** Creates new form DisplayManagement */
    public DisplayManagement(ArrayList<Agent> listAgent) {
        initComponents();
        this.setVisible(false);
        this.InitialisationColor();
        this.InitialisationPiePlot();
        jFrameWelcome.setVisible(true);
        dispEnv = new DisplayEnvironment(listAgent, listColorToOpinion);
        dispEnv.setBackground(Color.WHITE);
        dispEnv.setPreferredSize(new Dimension(500, 500));
        jInternalFrameDisplay.setContentPane(dispEnv);
        listLabel = new ArrayList<JLabel>();
        listLabel.add(jLabelNbOpinion0);
        listLabel.add(jLabelNbOpinion1);
        listLabel.add(jLabelNbOpinion2);
        listLabel.add(jLabelNbOpinion3);
        listLabel.add(jLabelNbOpinion4);
        listLabel.add(jLabelNbOpinion5);
        listLabel.add(jLabelNbOpinion6);
        listLabel.add(jLabelNbOpinion7);
        listLabel.add(jLabelNbOpinion8);
        listLabel.add(jLabelNbOpinion9);
        this.UpdateLabelSlide(jSliderNbAgent, jLabelSlideNbAgent);
        this.UpdateLabelSlide(jSliderDimEnv, jLabelSliderDImEnv);
        this.UpdateLabelSlide(jSliderArea, jLabelSliderArea);
        this.UpdateLabelSlide(jSliderStep, jLabelSliderStep);
        this.UpdateLabelSlide(jSliderWaitTime, jLabelSliderWaitTime);
        this.UpdateLabelSlide(jSliderTrust, jLabelSliderTrust);
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     /**
     * Initialization Color
     * @ author Alexandre C, Teddie
     */
    private void InitialisationColor() {
        listColorToOpinion = new TreeMap<Integer, Color>();
        listColorToOpinion.put(0, Color.DARK_GRAY);
        listColorToOpinion.put(1, Color.BLUE);
        listColorToOpinion.put(2, Color.YELLOW);
        listColorToOpinion.put(3, Color.RED);
        listColorToOpinion.put(4, Color.PINK);
        listColorToOpinion.put(5, Color.ORANGE);
        listColorToOpinion.put(6, Color.GREEN);
        listColorToOpinion.put(7, Color.MAGENTA);
        listColorToOpinion.put(8, Color.GRAY);
        listColorToOpinion.put(9, Color.CYAN);
    }
    /**
     * Initialization of Pie Plot
     * @ author Alexandre F, Teddie
     */
    private void InitialisationPiePlot() {
        data = new DefaultPieDataset();
        data.setValue("Opinion 0", 0);
        data.setValue("Opinion 1", 0);
        data.setValue("Opinion 2", 0);
        data.setValue("Opinion 3", 0);
        data.setValue("Opinion 4", 0);
        data.setValue("Opinion 5", 0);
        data.setValue("Opinion 6", 0);
        data.setValue("Opinion 7", 0);
        data.setValue("Opinion 8", 0);
        data.setValue("Opinion 9", 0);  
        JFreeChart g = ChartFactory.createPieChart3D("Représentation graphique du nombre de personnes par opinions", data, true, true, false);
        ChartPanel c = new ChartPanel(g);
        PiePlot3D plot = (PiePlot3D) g.getPlot();
        plot.setForegroundAlpha((float) 0.6);
        for (Map.Entry<Integer, Color> e : listColorToOpinion.entrySet()) {
            plot.setSectionPaint("Opinion " + e.getKey(), e.getValue());
        }
        BoxLayout Box = new BoxLayout(jPanelGraph, BoxLayout.PAGE_AXIS);
        jPanelGraph.setLayout(Box);
        this.jPanelGraph.add(c);
    }
    /**
     * @author Teddie
     * @param listAgentToOpinion
     */
    public void update(TreeMap<Integer, ArrayList<Agent>> listAgentToOpinion) {
        for (Map.Entry<Integer, ArrayList<Agent>> e : listAgentToOpinion.entrySet()) {
            Integer nb = e.getValue().size();
            listLabel.get(e.getKey()).setText(nb.toString());
            data.setValue("Opinion " + e.getKey(), nb);
            dispEnv.repaint();
        }
    }

    /**
     * @author Alexandre C, Teddie
     * @param j
     * @param l
     */
    private void UpdateLabelSlide(JSlider j, JLabel l) {
        Integer tmp = j.getValue();
        l.setText(tmp.toString());
    }
    //--------------------GETTER FOR SIMULATION-----------------//

    public int getNbAgent() {
        return jSliderNbAgent.getValue();
    }

    public int getWaitTime() {
        return jSliderWaitTime.getValue();
    }

    public int getDimEnv() {
        return jSliderDimEnv.getValue();
    }

    public int getArea() {
        return jSliderArea.getValue();
    }

    public int getStep() {
        return jSliderStep.getValue();
    }

    public int getTrust() {
        return jSliderTrust.getValue();
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameWelcome = new javax.swing.JFrame();
        jLabelInfo = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jLabelInitnbAgent = new javax.swing.JLabel();
        jLabelTrust = new javax.swing.JLabel();
        jLabelEnvDim = new javax.swing.JLabel();
        jLabelInteraction = new javax.swing.JLabel();
        jLabelPas = new javax.swing.JLabel();
        jButtonLoad1 = new javax.swing.JButton();
        jCheckBoxSave = new javax.swing.JCheckBox();
        jSliderNbAgent = new javax.swing.JSlider();
        jSliderDimEnv = new javax.swing.JSlider();
        jSliderArea = new javax.swing.JSlider();
        jSliderStep = new javax.swing.JSlider();
        jLabelSlideNbAgent = new javax.swing.JLabel();
        jLabelSliderDImEnv = new javax.swing.JLabel();
        jLabelSliderArea = new javax.swing.JLabel();
        jLabelSliderStep = new javax.swing.JLabel();
        jLabelWaitTime = new javax.swing.JLabel();
        jSliderWaitTime = new javax.swing.JSlider();
        jLabelSliderWaitTime = new javax.swing.JLabel();
        jSliderTrust = new javax.swing.JSlider();
        jLabelSliderTrust = new javax.swing.JLabel();
        jFileChooserSave = new javax.swing.JFileChooser();
        jFileChooserOpen = new javax.swing.JFileChooser();
        jPanelGraph = new javax.swing.JPanel();
        jPanelStat = new javax.swing.JPanel();
        jLabelOpinion0 = new javax.swing.JLabel();
        jLabelOpinion1 = new javax.swing.JLabel();
        jLabelOpinion2 = new javax.swing.JLabel();
        jLabelOpinion3 = new javax.swing.JLabel();
        jLabelOpinion5 = new javax.swing.JLabel();
        jLabelOpinion4 = new javax.swing.JLabel();
        jLabelOpinion6 = new javax.swing.JLabel();
        jLabelOpinion7 = new javax.swing.JLabel();
        jLabelOpinion8 = new javax.swing.JLabel();
        jLabelOpinion9 = new javax.swing.JLabel();
        jLabelNbOpinion1 = new javax.swing.JLabel();
        jLabelNbOpinion4 = new javax.swing.JLabel();
        jLabelNbOpinion7 = new javax.swing.JLabel();
        jLabelNbOpinion8 = new javax.swing.JLabel();
        jLabelNbOpinion5 = new javax.swing.JLabel();
        jLabelNbOpinion2 = new javax.swing.JLabel();
        jLabelNbOpinion6 = new javax.swing.JLabel();
        jLabelNbOpinion9 = new javax.swing.JLabel();
        jLabelNbOpinion3 = new javax.swing.JLabel();
        jLabelNbOpinion0 = new javax.swing.JLabel();
        jPanelAction = new javax.swing.JPanel();
        jLabelAgent = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jLabelActionNbAgent = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrameDisplay = new javax.swing.JInternalFrame();

        jFrameWelcome.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrameWelcome.setTitle("Bienvenue");
        jFrameWelcome.setMinimumSize(new java.awt.Dimension(600, 375));
        jFrameWelcome.setName("Welcome"); // NOI18N
        jFrameWelcome.setResizable(false);

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabelInfo.setText("Choix des paramètres de la simulation");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelInitnbAgent.setText("Nombre d'agents:");

        jLabelTrust.setText("Indice de confiance:");

        jLabelEnvDim.setText("Dimension de l'environnement:");

        jLabelInteraction.setText("Zone d'interaction:");

        jLabelPas.setText("Pas de déplacement:");

        jButtonLoad1.setText("Load");
        jButtonLoad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoad1ActionPerformed(evt);
            }
        });

        jCheckBoxSave.setText("Sauvegarder la simulation ");
        jCheckBoxSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaveActionPerformed(evt);
            }
        });

        jSliderNbAgent.setMaximum(500);
        jSliderNbAgent.setValue(250);
        jSliderNbAgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderNbAgentMouseClicked(evt);
            }
        });
        jSliderNbAgent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderNbAgentMouseDragged(evt);
            }
        });
        jSliderNbAgent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderNbAgentKeyPressed(evt);
            }
        });

        jSliderDimEnv.setMaximum(500);
        jSliderDimEnv.setMinimum(50);
        jSliderDimEnv.setValue(250);
        jSliderDimEnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderDimEnvMouseClicked(evt);
            }
        });
        jSliderDimEnv.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderDimEnvMouseDragged(evt);
            }
        });
        jSliderDimEnv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderDimEnvKeyPressed(evt);
            }
        });

        jSliderArea.setMaximum(500);
        jSliderArea.setMinimum(1);
        jSliderArea.setValue(250);
        jSliderArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderAreaMouseClicked(evt);
            }
        });
        jSliderArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderAreaMouseDragged(evt);
            }
        });
        jSliderArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderAreaKeyPressed(evt);
            }
        });

        jSliderStep.setMaximum(2);
        jSliderStep.setMinimum(1);
        jSliderStep.setValue(1);
        jSliderStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderStepMouseClicked(evt);
            }
        });
        jSliderStep.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderStepMouseDragged(evt);
            }
        });
        jSliderStep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderStepKeyPressed(evt);
            }
        });

        jLabelWaitTime.setText("Temps d'attente");

        jSliderWaitTime.setMaximum(60);
        jSliderWaitTime.setMinimum(1);
        jSliderWaitTime.setValue(30);
        jSliderWaitTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderWaitTimeMouseClicked(evt);
            }
        });
        jSliderWaitTime.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderWaitTimeMouseDragged(evt);
            }
        });
        jSliderWaitTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderWaitTimeKeyPressed(evt);
            }
        });

        jSliderTrust.setMaximum(5);
        jSliderTrust.setMinimum(1);
        jSliderTrust.setValue(3);
        jSliderTrust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderTrustMouseClicked(evt);
            }
        });
        jSliderTrust.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTrustMouseDragged(evt);
            }
        });
        jSliderTrust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSliderTrustKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jFrameWelcomeLayout = new javax.swing.GroupLayout(jFrameWelcome.getContentPane());
        jFrameWelcome.getContentPane().setLayout(jFrameWelcomeLayout);
        jFrameWelcomeLayout.setHorizontalGroup(
            jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabelInfo))
                    .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBoxSave)
                        .addGap(150, 150, 150)
                        .addComponent(jButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLoad1)))
                .addGap(176, 176, 176))
            .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInitnbAgent)
                    .addComponent(jLabelEnvDim)
                    .addComponent(jLabelInteraction)
                    .addComponent(jLabelWaitTime)
                    .addComponent(jLabelTrust)
                    .addComponent(jLabelPas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSliderTrust, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderDimEnv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderStep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jSliderNbAgent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderWaitTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelSliderTrust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSlideNbAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSliderStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSliderDImEnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSliderArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSliderWaitTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        jFrameWelcomeLayout.setVerticalGroup(
            jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                        .addComponent(jLabelInfo)
                        .addGap(18, 18, 18)
                        .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameWelcomeLayout.createSequentialGroup()
                                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInitnbAgent)
                                    .addComponent(jSliderNbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelWaitTime)
                                    .addComponent(jSliderWaitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSliderWaitTime))
                                .addGap(18, 18, 18)
                                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEnvDim)
                                    .addComponent(jLabelSliderDImEnv)
                                    .addComponent(jSliderDimEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSliderArea)
                                    .addComponent(jLabelInteraction)
                                    .addComponent(jSliderArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSliderStep)
                                    .addComponent(jSliderStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPas)))
                            .addComponent(jLabelSlideNbAgent))
                        .addGap(18, 18, 18)
                        .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderTrust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTrust))
                        .addGap(44, 44, 44)
                        .addGroup(jFrameWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxSave)
                            .addComponent(jButtonOk)
                            .addComponent(jButtonLoad1))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameWelcomeLayout.createSequentialGroup()
                        .addComponent(jLabelSliderTrust)
                        .addGap(114, 114, 114))))
        );

        jFileChooserSave.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Silmulateur d'opinion");
        setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jPanelGraphLayout = new javax.swing.GroupLayout(jPanelGraph);
        jPanelGraph.setLayout(jPanelGraphLayout);
        jPanelGraphLayout.setHorizontalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanelGraphLayout.setVerticalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        jLabelOpinion0.setText("Opinion 0");

        jLabelOpinion1.setText("Opinion 1");

        jLabelOpinion2.setText("Opinion 2");

        jLabelOpinion3.setText("Opinion 3");

        jLabelOpinion5.setText("Opinion 5");

        jLabelOpinion4.setText("Opinion 4");

        jLabelOpinion6.setText("Opinion 6");

        jLabelOpinion7.setText("Opinion 7");

        jLabelOpinion8.setText("Opinion 8");

        jLabelOpinion9.setText("Opinion 9");

        javax.swing.GroupLayout jPanelStatLayout = new javax.swing.GroupLayout(jPanelStat);
        jPanelStat.setLayout(jPanelStatLayout);
        jPanelStatLayout.setHorizontalGroup(
            jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpinion3)
                    .addComponent(jLabelNbOpinion3)
                    .addComponent(jLabelOpinion6)
                    .addComponent(jLabelNbOpinion6)
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion0)
                        .addGap(172, 172, 172)
                        .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOpinion1)
                            .addComponent(jLabelNbOpinion1)
                            .addComponent(jLabelNbOpinion4)
                            .addComponent(jLabelOpinion4)
                            .addComponent(jLabelNbOpinion7)
                            .addComponent(jLabelOpinion7)))
                    .addComponent(jLabelNbOpinion0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOpinion8)
                            .addComponent(jLabelNbOpinion8))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStatLayout.createSequentialGroup()
                            .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelOpinion5)
                                .addComponent(jLabelNbOpinion5))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatLayout.createSequentialGroup()
                            .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelOpinion2)
                                .addComponent(jLabelNbOpinion2))
                            .addContainerGap(133, Short.MAX_VALUE)))))
            .addGroup(jPanelStatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpinion9)
                    .addComponent(jLabelNbOpinion9))
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanelStatLayout.setVerticalGroup(
            jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpinion0)
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNbOpinion1))
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNbOpinion2)))
                .addGap(13, 13, 13)
                .addComponent(jLabelNbOpinion0, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNbOpinion5))
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNbOpinion4))
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNbOpinion3)))
                .addGap(19, 19, 19)
                .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStatLayout.createSequentialGroup()
                            .addComponent(jLabelOpinion6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelNbOpinion6))
                        .addGroup(jPanelStatLayout.createSequentialGroup()
                            .addComponent(jLabelOpinion7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelNbOpinion7)))
                    .addGroup(jPanelStatLayout.createSequentialGroup()
                        .addComponent(jLabelOpinion8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNbOpinion8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(27, 27, 27)
                .addComponent(jLabelOpinion9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNbOpinion9)
                .addGap(48, 48, 48))
        );

        jLabelAgent.setText("Nombre d'agents:");

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonStop.setText("Stop");

        javax.swing.GroupLayout jPanelActionLayout = new javax.swing.GroupLayout(jPanelAction);
        jPanelAction.setLayout(jPanelActionLayout);
        jPanelActionLayout.setHorizontalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStart))
                    .addComponent(jLabelAgent))
                .addGap(46, 46, 46)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelActionNbAgent)
                    .addComponent(jButtonStop))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanelActionLayout.setVerticalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAgent)
                    .addComponent(jLabelActionNbAgent))
                .addGap(42, 42, 42)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStart)
                    .addComponent(jButtonStop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrameDisplay.setResizable(true);
        jInternalFrameDisplay.setFocusable(false);
        jInternalFrameDisplay.setMaximumSize(new java.awt.Dimension(700, 700));
        jInternalFrameDisplay.setMinimumSize(new java.awt.Dimension(500, 500));
        jInternalFrameDisplay.setPreferredSize(new java.awt.Dimension(500, 500));
        jInternalFrameDisplay.setVisible(true);

        javax.swing.GroupLayout jInternalFrameDisplayLayout = new javax.swing.GroupLayout(jInternalFrameDisplay.getContentPane());
        jInternalFrameDisplay.getContentPane().setLayout(jInternalFrameDisplayLayout);
        jInternalFrameDisplayLayout.setHorizontalGroup(
            jInternalFrameDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        jInternalFrameDisplayLayout.setVerticalGroup(
            jInternalFrameDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(jPanelAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //------------------EVENT------------------//
    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
}//GEN-LAST:event_jButtonStartActionPerformed

    private void jCheckBoxSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaveActionPerformed
    }//GEN-LAST:event_jCheckBoxSaveActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed

        if (jCheckBoxSave.isSelected()) {
            jFileChooserSave.showSaveDialog(jFrameWelcome);
            pathSave = jFileChooserSave.getSelectedFile().getAbsolutePath();
        } else {
            this.setVisible(true);
        }
        jFrameWelcome.setVisible(false);
        Integer tmp = jSliderNbAgent.getValue();
        jLabelActionNbAgent.setText(tmp.toString());
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonLoad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoad1ActionPerformed
        jFileChooserOpen.showOpenDialog(jFrameWelcome);
    }//GEN-LAST:event_jButtonLoad1ActionPerformed

    private void jSliderNbAgentMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderNbAgentMouseDragged
        this.UpdateLabelSlide(jSliderNbAgent, jLabelSlideNbAgent);

    }//GEN-LAST:event_jSliderNbAgentMouseDragged

    private void jSliderNbAgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderNbAgentMouseClicked
        this.UpdateLabelSlide(jSliderNbAgent, jLabelSlideNbAgent);
    }//GEN-LAST:event_jSliderNbAgentMouseClicked

    private void jSliderNbAgentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderNbAgentKeyPressed
        this.UpdateLabelSlide(jSliderNbAgent, jLabelSlideNbAgent);
    }//GEN-LAST:event_jSliderNbAgentKeyPressed

    private void jSliderDimEnvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderDimEnvKeyPressed
        this.UpdateLabelSlide(jSliderDimEnv, jLabelSliderDImEnv);
    }//GEN-LAST:event_jSliderDimEnvKeyPressed

    private void jSliderDimEnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDimEnvMouseClicked
        this.UpdateLabelSlide(jSliderDimEnv, jLabelSliderDImEnv);
    }//GEN-LAST:event_jSliderDimEnvMouseClicked

    private void jSliderDimEnvMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderDimEnvMouseDragged
        this.UpdateLabelSlide(jSliderDimEnv, jLabelSliderDImEnv);
    }//GEN-LAST:event_jSliderDimEnvMouseDragged

    private void jSliderAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderAreaKeyPressed
        this.UpdateLabelSlide(jSliderArea, jLabelSliderArea);
    }//GEN-LAST:event_jSliderAreaKeyPressed

    private void jSliderAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderAreaMouseClicked
        this.UpdateLabelSlide(jSliderArea, jLabelSliderArea);
    }//GEN-LAST:event_jSliderAreaMouseClicked

    private void jSliderAreaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderAreaMouseDragged
        this.UpdateLabelSlide(jSliderArea, jLabelSliderArea);
    }//GEN-LAST:event_jSliderAreaMouseDragged

    private void jSliderStepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderStepKeyPressed
        this.UpdateLabelSlide(jSliderStep, jLabelSliderStep);
    }//GEN-LAST:event_jSliderStepKeyPressed

    private void jSliderStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderStepMouseClicked
        this.UpdateLabelSlide(jSliderStep, jLabelSliderStep);
    }//GEN-LAST:event_jSliderStepMouseClicked

    private void jSliderStepMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderStepMouseDragged
        this.UpdateLabelSlide(jSliderStep, jLabelSliderStep);
    }//GEN-LAST:event_jSliderStepMouseDragged

    private void jSliderWaitTimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderWaitTimeKeyPressed
        this.UpdateLabelSlide(jSliderWaitTime, jLabelSliderWaitTime);
    }//GEN-LAST:event_jSliderWaitTimeKeyPressed

    private void jSliderWaitTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderWaitTimeMouseClicked
        this.UpdateLabelSlide(jSliderWaitTime, jLabelSliderWaitTime);
    }//GEN-LAST:event_jSliderWaitTimeMouseClicked

    private void jSliderWaitTimeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderWaitTimeMouseDragged
        this.UpdateLabelSlide(jSliderWaitTime, jLabelSliderWaitTime);
    }//GEN-LAST:event_jSliderWaitTimeMouseDragged

    private void jSliderTrustKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderTrustKeyPressed
        this.UpdateLabelSlide(jSliderTrust, jLabelSliderTrust);
    }//GEN-LAST:event_jSliderTrustKeyPressed

    private void jSliderTrustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTrustMouseClicked
        this.UpdateLabelSlide(jSliderTrust, jLabelSliderTrust);
    }//GEN-LAST:event_jSliderTrustMouseClicked

    private void jSliderTrustMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTrustMouseDragged
       this.UpdateLabelSlide(jSliderTrust, jLabelSliderTrust);
    }//GEN-LAST:event_jSliderTrustMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoad1;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JCheckBox jCheckBoxSave;
    private javax.swing.JFileChooser jFileChooserOpen;
    private javax.swing.JFileChooser jFileChooserSave;
    private javax.swing.JFrame jFrameWelcome;
    private javax.swing.JInternalFrame jInternalFrameDisplay;
    private javax.swing.JLabel jLabelActionNbAgent;
    private javax.swing.JLabel jLabelAgent;
    private javax.swing.JLabel jLabelEnvDim;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInitnbAgent;
    private javax.swing.JLabel jLabelInteraction;
    private javax.swing.JLabel jLabelNbOpinion0;
    private javax.swing.JLabel jLabelNbOpinion1;
    private javax.swing.JLabel jLabelNbOpinion2;
    private javax.swing.JLabel jLabelNbOpinion3;
    private javax.swing.JLabel jLabelNbOpinion4;
    private javax.swing.JLabel jLabelNbOpinion5;
    private javax.swing.JLabel jLabelNbOpinion6;
    private javax.swing.JLabel jLabelNbOpinion7;
    private javax.swing.JLabel jLabelNbOpinion8;
    private javax.swing.JLabel jLabelNbOpinion9;
    private javax.swing.JLabel jLabelOpinion0;
    private javax.swing.JLabel jLabelOpinion1;
    private javax.swing.JLabel jLabelOpinion2;
    private javax.swing.JLabel jLabelOpinion3;
    private javax.swing.JLabel jLabelOpinion4;
    private javax.swing.JLabel jLabelOpinion5;
    private javax.swing.JLabel jLabelOpinion6;
    private javax.swing.JLabel jLabelOpinion7;
    private javax.swing.JLabel jLabelOpinion8;
    private javax.swing.JLabel jLabelOpinion9;
    private javax.swing.JLabel jLabelPas;
    private javax.swing.JLabel jLabelSlideNbAgent;
    private javax.swing.JLabel jLabelSliderArea;
    private javax.swing.JLabel jLabelSliderDImEnv;
    private javax.swing.JLabel jLabelSliderStep;
    private javax.swing.JLabel jLabelSliderTrust;
    private javax.swing.JLabel jLabelSliderWaitTime;
    private javax.swing.JLabel jLabelTrust;
    private javax.swing.JLabel jLabelWaitTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelGraph;
    private javax.swing.JPanel jPanelStat;
    private javax.swing.JSlider jSliderArea;
    private javax.swing.JSlider jSliderDimEnv;
    private javax.swing.JSlider jSliderNbAgent;
    private javax.swing.JSlider jSliderStep;
    private javax.swing.JSlider jSliderTrust;
    private javax.swing.JSlider jSliderWaitTime;
    // End of variables declaration//GEN-END:variables
}
